#ifndef KRYON_AUTHENTICATION_CHALLENGE_H
#define KRYON_AUTHENTICATION_CHALLENGE_H

/**
 * ----------------------------------------------------------
 * KRYON Research Framework
 * ----------------------------------------------------------
 * File : AuthenticationChallenge.h
 *
 * Description
 * -----------
 * Represents the challenge generated by the verifier
 * during the authentication process.
 *
 * Used by the Reference Authentication Protocol (RAP).
 * ----------------------------------------------------------
 */

#include <string>

namespace kryon
{

struct AuthenticationChallenge
{
    std::string challengeId;

    uint32_t sourceNodeId = 0;

    uint32_t destinationNodeId = 0;

    uint64_t challenge = 0;

    double timestamp = 0.0;
};

}

#endif
