#ifndef KRYON_AUTHENTICATION_CHALLENGE_H
#define KRYON_AUTHENTICATION_CHALLENGE_H

/**
 * ----------------------------------------------------------
 * KRYON Research Framework
 * ----------------------------------------------------------
 * File : AuthenticationChallenge.h
 *
 * Description
 * -----------
 * Represents the challenge generated by the verifier
 * during the authentication process.
 *
 * Used by the Reference Authentication Protocol (RAP).
 * ----------------------------------------------------------
 */

#include <string>
#include <vector>
#include <cstdint>
#include "../crypto/CryptoTypes.h"

namespace kryon
{

struct AuthenticationChallenge
{
    /*
 * Authentication session identifier.
 * Matches AuthenticationRequest::requestId.
 */
	std::string requestId;

    uint32_t sourceNodeId = 0;

    uint32_t destinationNodeId = 0;

    /*
 * Binary challenge generated by the verifier.
 */
	std::vector<uint8_t> challenge;
	
	/*
 * Verifier's public key.
 *
 * Used by the requester to verify the challenge signature.
 */
	PublicKey senderPublicKey;

/*
 * Digital signature over the challenge.
 *
 * Generated using the verifier's private ECC key.
 */
	Signature signature;

    double timestamp = 0.0;
};

}

#endif
