#ifndef KRYON_SECURITY_CONTEXT_H
#define KRYON_SECURITY_CONTEXT_H

/**
 * ----------------------------------------------------------
 * KRYON Research Framework
 * ----------------------------------------------------------
 * File : SecurityContext.h
 *
 * Description
 * -----------
 * Shared security state for the entire simulation.
 *
 * This context stores all information generated by
 * authentication, key agreement, trust management,
 * blockchain, DID, VC, ZKP, etc.
 * ----------------------------------------------------------
 */
#include "SecurityTypes.h"
#include "SecurityEvent.h"
#include "SecuritySession.h"
#include "SecurityStatistics.h"
#include <vector>
#include <string>
#include "AuthenticationContext.h"

namespace kryon
{

struct SecurityContext
{
    /* ---------- Authentication ---------- */

    bool authenticationEnabled = false;
	
	AuthenticationContext authentication;

    /* ---------- Trust ---------- */

    bool trustEnabled = false;

    /* ---------- Blockchain ---------- */

    bool blockchainEnabled = false;

   /* ---------- Active Sessions ---------- */

	std::vector<SecuritySession> sessions;

	/* ---------- Security Events ---------- */

	std::vector<SecurityEvent> events;

	/* ---------- Statistics ---------- */

	SecurityStatistics statistics;

	/* ---------- Future Session Keys ---------- */

	std::vector<std::string> sessionKeys;

};

}

#endif
