#ifndef KRYON_SECURITY_CONTEXT_H
#define KRYON_SECURITY_CONTEXT_H

/**
 * ----------------------------------------------------------
 * KRYON Research Framework
 * ----------------------------------------------------------
 * File : SecurityContext.h
 *
 * Description
 * -----------
 * Shared security state for the entire simulation.
 *
 * This context stores all information generated by
 * authentication, key agreement, trust management,
 * blockchain, DID, VC, ZKP, etc.
 * ----------------------------------------------------------
 */

#include <vector>
#include <string>

namespace kryon
{

struct SecurityContext
{
    /* ---------- Authentication ---------- */

    bool authenticationEnabled = false;

    /* ---------- Trust ---------- */

    bool trustEnabled = false;

    /* ---------- Blockchain ---------- */

    bool blockchainEnabled = false;

    /* ---------- Future Data ---------- */

    std::vector<std::string> sessionKeys;

};

}

#endif
