#ifndef KRYON_AUTHENTICATION_TRANSPORT_H
#define KRYON_AUTHENTICATION_TRANSPORT_H

/**
 * ----------------------------------------------------------
 * KRYON Research Framework
 * ----------------------------------------------------------
 * File : AuthenticationTransport.h
 *
 * Description
 * -----------
 * Simulates transmission of authentication packets through
 * the ns-3 network.
 *
 * Current Version
 * ---------------
 * - Schedules packet delivery events
 * - Logs packet transmission
 * - Ready for future UDP socket integration
 *
 * Future Version
 * --------------
 * - Real UDP socket communication
 * - Packet loss simulation
 * - Wireless propagation delay
 * - Multi-hop forwarding
 * ----------------------------------------------------------
 */

#include "../../core/ExperimentConfig.h"
#include "../../simulation/SimulationContext.h"
#include "../../core/Logger.h"

#include "../packets/AuthRequestPacket.h"
#include "../packets/AuthChallengePacket.h"
#include "../packets/AuthResponsePacket.h"
#include "../packets/AuthConfirmPacket.h"
#include "AuthenticationReceiver.h"
#include "AuthenticationMessageCodec.h"
#include <cstdint>
#include "ns3/core-module.h"

#include <functional>

namespace kryon
{

class AuthenticationTransport
{
public:

	using RequestHandler =
    std::function<void(const AuthRequestPacket&)>;

    AuthenticationTransport(
        const ExperimentConfig& config,
        SimulationContext& context)
        :
        m_config(config),
        m_context(context)
    {
		   m_receiver.SetDispatcher(&m_dispatcher);
    }

    /* ------------------------------------------------------
     * Initialize
     * ------------------------------------------------------*/

    void Initialize()
    {
        Logger::Info("Authentication Transport initialized.");
    }
    
	void RegisterRequestHandler(RequestHandler handler)
	{
		m_requestHandler = handler;
	}

    /* ------------------------------------------------------
     * Send Request Packet
     * ------------------------------------------------------*/

	
	void SendRequest(
    const AuthRequestPacket& packet)
{
    Logger::Info(
        "[Transport] Sending AuthRequestPacket (" +
        packet.requestId +
        ") from Drone " +
        std::to_string(packet.sourceNode) +
        " to Vehicle " +
        std::to_string(packet.destinationNode));

    ns3::Ptr<ns3::Packet> udpPacket =
        AuthenticationMessageCodec::Encode(packet);

    Logger::Info(
        "[Transport] Encoded packet size = " +
        std::to_string(udpPacket->GetSize()) +
        " bytes");

   uint32_t droneIndex = UINT32_MAX;
	uint32_t vehicleIndex = UINT32_MAX;

	/*
	 * Resolve actual ns-3 Node ID -> container index.
	 */
	for (uint32_t i = 0; i < m_context.drones.GetN(); ++i)
	{
		if (m_context.drones.Get(i)->GetId() ==
			packet.sourceNode)
		{
			droneIndex = i;
			break;
		}
	}

	for (uint32_t i = 0; i < m_context.avs.GetN(); ++i)
	{
		if (m_context.avs.Get(i)->GetId() ==
			packet.destinationNode)
		{
			vehicleIndex = i;
			break;
		}
	}

	if (droneIndex == UINT32_MAX)
	{
		Logger::Warning(
			"[Transport] Invalid source drone Node ID: " +
			std::to_string(packet.sourceNode));
		return;
	}

	if (vehicleIndex == UINT32_MAX)
	{
		Logger::Warning(
			"[Transport] Invalid destination vehicle Node ID: " +
			std::to_string(packet.destinationNode));
		return;
	}
ns3::Ptr<ns3::Socket> socket =
    m_context.droneSockets[droneIndex];

ns3::Ipv4Address destinationIp =
    m_context.avInterfaces.GetAddress(
        vehicleIndex);

int sent =
    socket->SendTo(
        udpPacket,
        0,
        ns3::InetSocketAddress(
            destinationIp,
            9000));

Logger::Info(
    "[Transport] UDP SendTo result = " +
    std::to_string(sent));

if (sent < 0)
{
    Logger::Warning(
        "[Transport] UDP authentication packet send FAILED.");
}

}


void ReceiveUdpPacket(ns3::Ptr<ns3::Packet> udpPacket)
{
    uint32_t packetSize = udpPacket->GetSize();

    Logger::Info(
        "[Transport] UDP authentication packet received (" +
        std::to_string(packetSize) +
        " bytes)");

    //
    // Temporary separation:
    // Current KRYON AuthRequestPacket is a serialized
    // variable-length packet, currently 39 bytes.
    //
    // The 836-byte packets generated by ApplicationEngine
    // are raw application traffic and must not be decoded
    // as AuthRequestPacket.
    //
 

    try
    {
        AuthRequestPacket request =
            AuthenticationMessageCodec::DecodeRequest(
                udpPacket);

        Logger::Info(
            "[Transport] Decoded AuthRequestPacket (" +
            request.requestId +
            ")");

        m_receiver.Receive(request);
    }
    catch (const std::exception& e)
    {
        Logger::Warning(
            "[Transport] Failed to decode authentication packet: " +
            std::string(e.what()));
    }
    catch (...)
    {
        Logger::Warning(
            "[Transport] Failed to decode authentication packet.");
    }
}

void AttachVehicleSocket(
    ns3::Ptr<ns3::Socket> socket)
{
    if (socket == nullptr)
    {
        Logger::Warning(
            "[Transport] Cannot attach null vehicle socket.");
        return;
    }

    socket->SetRecvCallback(
        ns3::MakeCallback(
            &AuthenticationTransport::HandleSocketReceive,
            this));

    Logger::Info(
        "[Transport] Authentication receive callback attached.");
}


void HandleSocketReceive(ns3::Ptr<ns3::Socket> socket)
{
    while (ns3::Ptr<ns3::Packet> packet = socket->Recv())
    {
        ReceiveUdpPacket(packet);
    }
}
    /* ------------------------------------------------------
     * Finalize
     * ------------------------------------------------------*/

    void Finalize()
    {
        Logger::Info("Authentication Transport finalized.");
    }
	
	AuthenticationReceiver& GetReceiver()
	{
		return m_receiver;
	}

	AuthenticationDispatcher& GetDispatcher()
	{
		return m_dispatcher;
	}


private:

 /*void DeliverRequest(
    ns3::Ptr<ns3::Packet> udpPacket,
    std::string requestId)
{
    Logger::Info(
        "[Transport] Delivered AuthRequestPacket (" +
        requestId + ")");

    AuthRequestPacket decodedRequest =
        AuthenticationMessageCodec::DecodeRequest(
            udpPacket);

    m_receiver.Receive(decodedRequest);
}*/
private:

    const ExperimentConfig& m_config;

    SimulationContext& m_context;
	
	AuthenticationReceiver m_receiver;
	AuthenticationDispatcher m_dispatcher;
	RequestHandler m_requestHandler;
	

};

}

#endif
